version: '3'

services:

  wpdb:
    image: mysql:5.7
    volumes:
       - db-data:/var/lib/mysql
    restart: always  
    ports:
      - 3315:3306
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress

  wordpress:
    image: wordpress:4.8.3-php5.6-apache
    container_name: cc-wp
    depends_on:
       - wpdb    
    ports:
      - 9000:80
    restart: always
    volumes:
      - ./ccbr-theme:/var/www/html/wp-content/themes/ccbr-theme
      - ./uploads:/var/www/html/wp-content/uploads
      - ./plugins:/var/www/html/wp-content/plugins
    links:
      - wpdb
    environment:
      WORDPRESS_DB_HOST: wpdb:3306       
      WORDPRESS_DB_PASSWORD: somewordpress
      GOOGLE_MAPS_API_KEY: AIzaSyDoZFn11-WmecouAx2hVxfrAt5wP-XjUPE
      CCW_API_READWRITE_TOKEN: RWd24531c067de3287813345b4fc538b6d2da9e858cf560de0cf34df286ed33e2d
      CCW_API_READONLY_TOKEN: RObf83e126283b38f1e512429cb4539ab360aabda9f41682348af5a8aed530c2aa
      TYPEKIT_ID: hos3npy

volumes:
    db-data:
